name = "moscowrooftop-site"
main = "src/index.js"
compatibility_date = "2026-07-05"
workers_dev = true

[assets]
directory = "."
binding = "ASSETS"
run_worker_first = true
html_handling = "none"
not_found_handling = "404-page"

[[routes]]
pattern = "moscowrooftop.ru"
custom_domain = true

[[routes]]
pattern = "www.moscowrooftop.ru"
custom_domain = true
